### ISSUE TITLE
128 unresolved externals in leptonica-1.81.0

### ISSUE THREAD

**Issue by gitgitwhat** [DanBloomberg/leptonica#550] opened 2020-10-28 14:25 UTC
I was able to successfully build tesseract and leptonica using VS2019 however when I try to link leptonica into my DLL, I get a whole bunch of LNK2019 unresolved symbol errors.  Before you ask, yes I have the library and header paths set and the libraries (tesseract50.lib, leptonica-1.81.0.lib) imported.  Are there other libraries that need imported or a setting that I'm missing?  

I'm trying to build a very simple example very similiar to the code below.  

```
#include <tesseract\baseapi.h>
#include <leptonica\allheaders.h>
#include <iostream>

using namespace std;

int main(void){
    tesseract::TessBaseAPI api;
    api.Init("", "eng", tesseract::OEM_DEFAULT);
    api.SetPageSegMode(static_cast<tesseract::PageSegMode>(7));
    api.SetOutputName("out");

    cout<<"File name:";
    char image[256];
    cin>>image;
    PIX   *pixs = pixRead(image);

    STRING text_out;
    api.ProcessPages(image, NULL, 0, &text_out);

    cout<<text_out.string();
    system("pause");
}
```

**Environment**
-Windows 10 x64
-VS2019

**Commands Used to Build Tesseract and Leptonica**
cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=Release
cmake --build . --config Release --target install

**Output When Building DLL**
```
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol EGifOpen referenced in function pixWriteStreamGif
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol EGifCloseFile referenced in function pixWriteStreamGif
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol EGifPutScreenDesc referenced in function "int __cdecl pixToGif(struct Pix *,struct GifFileType *)" (?pixToGif@@YAHPEAUPix@@PEAUGifFileType@@@Z)
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol EGifPutImageDesc referenced in function "int __cdecl pixToGif(struct Pix *,struct GifFileType *)" (?pixToGif@@YAHPEAUPix@@PEAUGifFileType@@@Z)
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol EGifPutLine referenced in function "int __cdecl pixToGif(struct Pix *,struct GifFileType *)" (?pixToGif@@YAHPEAUPix@@PEAUGifFileType@@@Z)
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol EGifPutComment referenced in function "int __cdecl pixToGif(struct Pix *,struct GifFileType *)" (?pixToGif@@YAHPEAUPix@@PEAUGifFileType@@@Z)
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol DGifSlurp referenced in function "struct Pix * __cdecl gifToPix(struct GifFileType *)" (?gifToPix@@YAPEAUPix@@PEAUGifFileType@@@Z)
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol DGifOpen referenced in function pixReadStreamGif
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol DGifCloseFile referenced in function "struct Pix * __cdecl gifToPix(struct GifFileType *)" (?gifToPix@@YAPEAUPix@@PEAUGifFileType@@@Z)
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol GifMakeMapObject referenced in function "int __cdecl pixToGif(struct Pix *,struct GifFileType *)" (?pixToGif@@YAHPEAUPix@@PEAUGifFileType@@@Z)
1>leptonica-1.81.0.lib(gifio.obj) : error LNK2019: unresolved external symbol GifFreeMapObject referenced in function "int __cdecl pixToGif(struct Pix *,struct GifFileType *)" (?pixToGif@@YAHPEAUPix@@PEAUGifFileType@@@Z)
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_version referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_image_create referenced in function "struct opj_image * __cdecl pixConvertToOpjImage(struct Pix *)" (?pixConvertToOpjImage@@YAPEAUopj_image@@PEAUPix@@@Z)
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_image_destroy referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_stream_create referenced in function "void * * __cdecl opjCreateStream(struct _iobuf *,int)" (?opjCreateStream@@YAPEAPEAXPEAU_iobuf@@H@Z)
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_stream_destroy referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_stream_set_read_function referenced in function "void * * __cdecl opjCreateStream(struct _iobuf *,int)" (?opjCreateStream@@YAPEAPEAXPEAU_iobuf@@H@Z)
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_stream_set_write_function referenced in function "void * * __cdecl opjCreateStream(struct _iobuf *,int)" (?opjCreateStream@@YAPEAPEAXPEAU_iobuf@@H@Z)
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_stream_set_skip_function referenced in function "void * * __cdecl opjCreateStream(struct _iobuf *,int)" (?opjCreateStream@@YAPEAPEAXPEAU_iobuf@@H@Z)
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_stream_set_seek_function referenced in function "void * * __cdecl opjCreateStream(struct _iobuf *,int)" (?opjCreateStream@@YAPEAPEAXPEAU_iobuf@@H@Z)
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_stream_set_user_data referenced in function "void * * __cdecl opjCreateStream(struct _iobuf *,int)" (?opjCreateStream@@YAPEAPEAXPEAU_iobuf@@H@Z)
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_stream_set_user_data_length referenced in function "void * * __cdecl opjCreateStream(struct _iobuf *,int)" (?opjCreateStream@@YAPEAPEAXPEAU_iobuf@@H@Z)
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_set_info_handler referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_set_warning_handler referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_set_error_handler referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_create_decompress referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_destroy_codec referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_end_decompress referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_set_default_decoder_parameters referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_setup_decoder referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_read_header referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_set_decode_area referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_decode referenced in function pixReadStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_create_compress referenced in function pixWriteStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_set_default_encoder_parameters referenced in function pixWriteStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_setup_encoder referenced in function pixWriteStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_start_compress referenced in function pixWriteStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_end_compress referenced in function pixWriteStreamJp2k
1>leptonica-1.81.0.lib(jp2kio.obj) : error LNK2019: unresolved external symbol opj_encode referenced in function pixWriteStreamJp2k
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_std_error referenced in function pixReadStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_CreateCompress referenced in function pixWriteStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_CreateDecompress referenced in function pixReadStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_destroy_compress referenced in function pixWriteStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_destroy_decompress referenced in function pixReadStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_stdio_dest referenced in function pixWriteStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_stdio_src referenced in function pixReadStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_set_defaults referenced in function pixWriteStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_set_quality referenced in function pixWriteStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_simple_progression referenced in function pixWriteStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_start_compress referenced in function pixWriteStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_write_scanlines referenced in function pixWriteStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_finish_compress referenced in function pixWriteStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_write_marker referenced in function pixWriteStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_read_header referenced in function pixReadStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_start_decompress referenced in function pixReadStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_read_scanlines referenced in function pixReadStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_finish_decompress referenced in function pixReadStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_calc_output_dimensions referenced in function pixReadStreamJpeg
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_set_marker_processor referenced in function fgetJpegComment
1>leptonica-1.81.0.lib(jpegio.obj) : error LNK2019: unresolved external symbol jpeg_destroy referenced in function "void __cdecl jpeg_error_catch_all_1(struct jpeg_common_struct *)" (?jpeg_error_catch_all_1@@YAXPEAUjpeg_common_struct@@@Z)
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_create_read_struct referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_create_write_struct referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_longjmp_fn referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_create_info_struct referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_write_info referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_read_info referenced in function fgetPngResolution
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_write_row referenced in function pixWriteMemPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_write_rows referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_write_image referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_write_end referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_destroy_read_struct referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_destroy_write_struct referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_compression_level referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_init_io referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_write_fn referenced in function pixWriteMemPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_read_fn referenced in function pixReadMemPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_io_ptr referenced in function "void __cdecl memio_png_write_data(struct png_struct_def *,unsigned char *,unsigned __int64)" (?memio_png_write_data@@YAXPEAUpng_struct_def@@PEAE_K@Z)
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_error referenced in function "void __cdecl memio_png_read_data(struct png_struct_def *,unsigned char *,unsigned __int64)" (?memio_png_read_data@@YAXPEAUpng_struct_def@@PEAE_K@Z)
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_valid referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_rowbytes referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_rows referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_rows referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_channels referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_image_width referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_image_height referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_bit_depth referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_color_type referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_x_pixels_per_meter referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_y_pixels_per_meter referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_gAMA referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_IHDR referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_pHYs referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_PLTE referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_PLTE referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_text referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_text referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_get_tRNS referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_set_tRNS referenced in function pixWriteStreamPng
1>leptonica-1.81.0.lib(pngio.obj) : error LNK2019: unresolved external symbol png_read_png referenced in function pixReadStreamPng
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFCleanup referenced in function pixReadTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFClose referenced in function pixWriteTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFGetField referenced in function freadHeaderTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFGetFieldDefaulted referenced in function freadHeaderTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFReadDirectory referenced in function pixReadFromMultipageTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFScanlineSize referenced in function "struct Pix * __cdecl pixReadFromTiffStream(struct tiff *)" (?pixReadFromTiffStream@@YAPEAUPix@@PEAUtiff@@@Z)
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFIsTiled referenced in function "struct Pix * __cdecl pixReadFromTiffStream(struct tiff *)" (?pixReadFromTiffStream@@YAPEAUPix@@PEAUtiff@@@Z)
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFCurrentDirOffset referenced in function pixReadFromMultipageTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFSetDirectory referenced in function pixReadTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFSetSubDirectory referenced in function pixReadFromMultipageTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFSetField referenced in function "int __cdecl pixWriteToTiffStream(struct tiff *,struct Pix *,int,struct Numa *,struct Sarray *,struct Sarray *,struct Numa *)" (?pixWriteToTiffStream@@YAHPEAUtiff@@PEAUPix@@HPEAUNuma@@PEAUSarray@@32@Z)
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFPrintDirectory referenced in function fprintTiffInfo
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFReadScanline referenced in function "struct Pix * __cdecl pixReadFromTiffStream(struct tiff *)" (?pixReadFromTiffStream@@YAPEAUPix@@PEAUtiff@@@Z)
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFWriteScanline referenced in function "int __cdecl pixWriteToTiffStream(struct tiff *,struct Pix *,int,struct Numa *,struct Sarray *,struct Sarray *,struct Numa *)" (?pixWriteToTiffStream@@YAHPEAUtiff@@PEAUPix@@HPEAUNuma@@PEAUSarray@@32@Z)
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFReadRGBAImageOriented referenced in function "struct Pix * __cdecl pixReadFromTiffStream(struct tiff *)" (?pixReadFromTiffStream@@YAPEAUPix@@PEAUtiff@@@Z)
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFOpen referenced in function pixWriteTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFClientOpen referenced in function pixReadTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFSetErrorHandler referenced in function pixReadTiff
1>leptonica-1.81.0.lib(tiffio.obj) : error LNK2019: unresolved external symbol TIFFSetWarningHandler referenced in function pixReadTiff
1>leptonica-1.81.0.lib(webpio.obj) : error LNK2019: unresolved external symbol WebPDecodeRGBAInto referenced in function pixReadStreamWebP
1>leptonica-1.81.0.lib(webpio.obj) : error LNK2019: unresolved external symbol WebPGetFeaturesInternal referenced in function pixReadStreamWebP
1>leptonica-1.81.0.lib(webpio.obj) : error LNK2019: unresolved external symbol WebPEncodeRGBA referenced in function pixWriteMemWebP
1>leptonica-1.81.0.lib(webpio.obj) : error LNK2019: unresolved external symbol WebPEncodeLosslessRGBA referenced in function pixWriteMemWebP
1>leptonica-1.81.0.lib(zlibmem.obj) : error LNK2019: unresolved external symbol deflate referenced in function zlibCompress
1>leptonica-1.81.0.lib(zlibmem.obj) : error LNK2019: unresolved external symbol deflateEnd referenced in function zlibCompress
1>leptonica-1.81.0.lib(zlibmem.obj) : error LNK2019: unresolved external symbol inflate referenced in function zlibUncompress
1>leptonica-1.81.0.lib(zlibmem.obj) : error LNK2019: unresolved external symbol inflateEnd referenced in function zlibUncompress
1>leptonica-1.81.0.lib(zlibmem.obj) : error LNK2019: unresolved external symbol deflateInit_ referenced in function zlibCompress
1>leptonica-1.81.0.lib(zlibmem.obj) : error LNK2019: unresolved external symbol inflateInit_ referenced in function zlibUncompress
fatal error LNK1120: 128 unresolved externals
```

**Comment by stweil** [comment] 2020-10-28 17:29
As you can see from the linker errors, all libraries for the different image formats (GIF, JPEG, JPEG2000, PNG, TIFF, ...) are missing in your build.

This is not a Leptonica issue!

Please use the documentation for building Tesseract with Leptonica.

**Comment by gitgitwhat** [comment] 2020-10-28 18:47
> 
> 
> As you can see from the linker errors, all libraries for the different image formats (GIF, JPEG, JPEG2000, PNG, TIFF, ...) are missing in your build.
> 
> This is not a Leptonica issue!
> 
> Please use the documentation for building Tesseract with Leptonica.

Thanks for the reply but I built Tesseract and Leptonica according the docs.  Maybe I missed it but where does it talk about having to build all these other libraries?  If Leptonica requires these libraries but doesn't supply them then it is a Leptonica issue.

**Comment by DanBloomberg** [comment] 2020-11-22 02:11
Actually, leptonica does not require those libraries, and can be built without them.  Most of the regression tests in leptonica can also be run without external I/O libraries, although it's unusual to do that.

However, tesseract requires several libraries, including leptonica and some of these I/O libraries.   So again, this is not a leptonica issue.

**Comment by tdhintz** [comment] 2021-02-05 19:53
I had the same issue in Visual Studio 2019 because Additional Dependencies was blank. I went back to a previously built project and copied over the dependencies manually.  Because I had move workstations since then I was forced to go through the sw cache and update the location and version numbers, but that resolved the dependencies issue for me.

**Comment by DanBloomberg** [comment] 2021-06-13 21:53
closing this issue

**Closed by DanBloomberg** 2021-06-13 21:53 UTC
