### ISSUE TITLE
Unable to build leptonica.dll.

### ISSUE THREAD

**Issue by naushadck** [DanBloomberg/leptonica#703] opened 2023-07-18 08:11 UTC
Hello, 

Building Leptonica in Windows 10 using cmake/Visual Studio 2022

1. It is building .lib file successfully.
2. Unable to build the same project in to .dll file. 

 Leptonica.lib is generated. How can i generate Leptonica.dll .
Any special steps to be followed ?.  Appreciate your help.

**Comment by naushadck** [comment] 2023-08-02 13:58
I got the solution from issue #375

Following steps worked for me 

mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=1 -DSW_BUILD_SHARED_LIBS=0 ..
cmake --build .  --config release

Thanks to [egorpugin](https://github.com/egorpugin)

**Comment by DanBloomberg** [comment] 2023-08-02 14:51
@egorpugin 

Hi Egor,

I am looking at the README.html.  In the section (3) Using cmake, starting at line 291, it says the default is to build shared libraries, and there is no discussion of dlls.  Also no mention of DSW_BUILD_SHARED_LIBS.

Can you please add the relevant information from this issue?

Dan

**Comment by egorpugin** [comment] 2023-08-02 21:13
Hi,

I've added the following comment there.

```
       * To make a dynamic library (default) and STATIC (or builtin) dependencies:
            cmake .. -DSW_BUILD_SHARED_LIBS=0
            make
```

**Comment by DanBloomberg** [comment] 2023-08-02 22:11
Thanks Egor.  Closing because the issue is resolved.

**Closed by DanBloomberg** 2023-08-02 22:11 UTC
