### ISSUE TITLE
No rule to install ??????

### ISSUE THREAD

**Issue by jiapei100** [DanBloomberg/leptonica#131] opened 2016-03-19 08:21 UTC
========================= Installation results ===========================
make: *** No rule to make target `install'.  Stop.

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

**Comment by chewi** [comment] 2016-04-13 22:06
See #117 or use autotools instead of CMake.

**Comment by DanBloomberg** [comment] 2016-04-14 02:06
duplicate of #117

**Closed by DanBloomberg** 2016-04-14 02:06 UTC
