### ISSUE TITLE
MSVC2015: INT32 redefined

### ISSUE THREAD

**Issue by xsacha** [DanBloomberg/leptonica#260] opened 2017-06-06 00:04 UTC
jpeglib.h defined INT32 before Windows resulting in a redefine. jpeglib.h has a proper check as long as the Windows header is included first.

See: https://github.com/xsacha/leptonica/commit/f74158a38db37d3ffe46c85884806f3cf00b0687

**Comment by DanBloomberg** [comment] 2018-02-09 23:32
Closing (assuming the issue is either resolved or moot)

**Closed by DanBloomberg** 2018-02-09 23:32 UTC
