### ISSUE TITLE
read Jpeg and PNG produce wrong alpha in 32bpp pix

### ISSUE THREAD

**Issue by alexcohn** [DanBloomberg/leptonica#442] opened 2019-06-30 22:44 UTC
In [tesseract 4 Android](https://github.com/rmtheis/tess-two) (and its multiple forks, including a recent [rewrite](https://github.com/adaptech-cz/Tesseract4Android)), we use **pix** with 32bpp.

It happens so that some Java tests written for image file i/o fail, because the underlying **pngio.c** and **jpegio.c** don't set the **L_ALPHA_CHANNEL** byte to **255**. For **JPG** this is unconditional; for **PNG**, when **spp == 3**.

**Comment by DanBloomberg** [comment] 2019-06-30 23:01
There are two issues (png and jpeg).

png: would it solve the problems if when writing 3 spp png, do the same, set the alpha sample to 255?

jpeg: I don't understand the problem, because jpeg compressed files do not have an alpha channel; they have spp = 1 or 3, only.

**Comment by DanBloomberg** [comment] 2019-06-30 23:05
I see, the failure is on the pix after reading -- you want the alpha byte to be set to 255 for all spp =3 pix.

**Comment by alexcohn** [comment] 2019-06-30 23:05
Yup.

**Comment by alexcohn** [comment] 2019-06-30 23:07
I don't think you *can* set alpha to 255 when the PNG is 3spp, it's ***assumed*** that in this case, opacity is full.

**Comment by alexcohn** [comment] 2019-06-30 23:09
The only question is, how this failing test has triggered nobody before. Well, some WriteFile tests in tesseract for Android fail, too; but I chose to begin with read.

**Comment by DanBloomberg** [comment] 2019-06-30 23:19
We agree, the fix would be in reading a pix.  But really, the issue is what the test does with that pix.

I would guess that the test is flaky.  We have an spp == 3 pix, and the assumption should be that the 4th byte in the pix can be anything.  It should never be tested.

**Comment by alexcohn** [comment] 2019-06-30 23:25
OK, this definitely explains how such thing passed under the radar. The Java wrapper at https://github.com/rmtheis/tess-two/blob/master/tess-two/src/com/googlecode/leptonica/android/Pix.java does not expose **Pix.spp**, thus the tests fail.

**Comment by DanBloomberg** [comment] 2019-07-01 17:06
fix the java tests.  See my last comment in #443

**Comment by alexcohn** [comment] 2019-07-03 09:22
I have fixed the Java tests in [my fork](https://github.com/alexcohn/Tesseract4Android). of Tesseract 4 Android. For that purpose, I have exposed **spp** and **imageFormat** to Java.

**Comment by DanBloomberg** [comment] 2019-07-21 04:51
resolved in leptonica

**Closed by DanBloomberg** 2019-07-21 04:51 UTC
