### ISSUE TITLE
webpio_reg test failure on big endian (ppc64, s390x)

### ISSUE THREAD

**Issue by manisandro** [DanBloomberg/leptonica#307] opened 2018-02-11 23:22 UTC
Hi,
Noticed this when attempting to update the Fedora package to 1.75.2 (https://koji.fedoraproject.org/koji/taskinfo?taskID=24954012)

    FAIL: webpio_reg
    ================
    ################   webpio_reg   ###############
    leptonica-1.75.2
    libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1
    Time to read jpg:   0.000
    Time to write webp:   0.005
    Time to read webp:   0.000
    Time to read jpg:   0.000
    Time to write webp:   0.000
    Time to read webp:   0.000
    Time to read jpg:   0.000
    Time to write webp:   0.069
    Time to read webp:   0.010
    Time to read jpg:   0.009
    Time to write webp:   0.515
    Time to read webp:   0.049
    qual = 50, psnr =  43.501
    qual = 75, psnr =  46.071
    qual = 90, psnr =  52.379
    qual = 100, psnr =  57.460
    Lossless write:   0.871 sec
    lossless; psnr should be 1000: psnr =  23.222
    Failure in webpio_reg: value comparison for index 12
    difference = 976.777893 but allowed delta = 0.100000
    Time:   3.986 sec
    ################################################

**Comment by DanBloomberg** [comment] 2018-02-12 00:45
I don't understand the variability.  Here's what I get on linux, also using 0.6.1

leptonica-1.75.2
libgif 5.1.1 : libjpeg 8 : libpng 1.2.35 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.6.1 : libopenjp2 2.3.0

Time to read jpg:   0.000
Time to write webp:   0.000
Time to read webp:   0.000
Time to read jpg:   0.000
Time to write webp:   0.004
Time to read webp:   0.000
Time to read jpg:   0.000
Time to write webp:   0.032
Time to read webp:   0.000
Time to read jpg:   0.020
Time to write webp:   0.160
Time to read webp:   0.020
qual = 50, psnr =  43.203
qual = 75, psnr =  45.782
qual = 90, psnr =  51.077
qual = 100, psnr =  54.635
Lossless write:   0.468 sec
lossless; psnr should be 1000: psnr = 1000.000
Time:   1.476 sec

Note that the psnr are different for all quality factors between the report and my numbers.

**Comment by jbreiden** [comment] 2018-02-12 13:49
Webp requires little endian data and is probably being fed host byte ordering.

**Comment by DanBloomberg** [comment] 2018-02-13 17:07
[webpio.c.gz](https://github.com/DanBloomberg/leptonica/files/1720834/webpio.c.gz)
@manisandro 

Here is a patched version of webpio.c.  Can you please test webpio_reg on a big-endian machine to see if this fixes the problem?

Thanks.

**Comment by manisandro** [comment] 2018-02-13 17:25
Thanks for the quick patch. Unfortunately, it still fails (https://kojipkgs.fedoraproject.org//work/tasks/7176/25007176/build.log):

    FAIL: webpio_reg
    ================
    ################   webpio_reg   ###############
    leptonica-1.75.2
    libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1
    Time to read jpg:   0.000
    Time to write webp:   0.000
    Time to read webp:   0.000
    Failure in webpio_reg: pix similarity comp for index 1
    Time to read jpg:   0.000
    Time to write webp:   0.008
    Time to read webp:   0.000
    Failure in webpio_reg: pix similarity comp for index 3
    Time to read jpg:   0.000
    Time to write webp:   0.168
    Time to read webp:   0.010
    Time to read jpg:   0.010
    Time to write webp:   1.666
    Time to read webp:   0.078
    qual = 50, psnr =  42.006
    Failure in webpio_reg: value comparison for index 8
    difference = 1.494339 but allowed delta = 1.000000
    qual = 75, psnr =  43.495
    Failure in webpio_reg: value comparison for index 9
    difference = 2.574799 but allowed delta = 1.000000
    qual = 90, psnr =  46.048
    Failure in webpio_reg: value comparison for index 10
    difference = 5.041767 but allowed delta = 2.000000
    qual = 100, psnr =  47.222
    Failure in webpio_reg: value comparison for index 11
    difference = 7.756729 but allowed delta = 5.000000
    Lossless write:   0.956 sec
    lossless; psnr should be 1000: psnr =  20.938
    Failure in webpio_reg: value comparison for index 12
    difference = 979.061584 but allowed delta = 0.100000
    Time:  10.060 sec
    ################################################

**Comment by DanBloomberg** [comment] 2018-02-13 21:12
@manisandro 

Wow!  It's much worse.

Can you look at the images that it is making?  If there is a byte order problem, it will be obvious by inspection.  Most image display programs don't handle webp, but the browser does:  e.g.
   file:///tmp/lept/golden/webpio_golden.04.webp
   file:///tmp/lept/golden/webpio_golden.06.webp
   
Please look at these images before and after the latest patch on webpio.  You can also add them to this bug so I can see them as well.

Thanks so much!

**Comment by DanBloomberg** [comment] 2018-02-13 21:17
@manisandro 

If this is a byte order issue, it is most likely messing it up on either the write or the read of webp.

If the written images look OK in the browser, then it's likely that the problem is in the reading. To check that, you can do two things:
(1) add a call to pixDisplay(pix, 0, 0) and look at the image after you've read it back in
(2) comment out the call to pixDoEndianByteSwap() in line 154 of the read function

If the written images are byte-order corrupted, try commenting out pixDoEndianByteSwap() in line 394 of the write function.

**Comment by manisandro** [comment] 2018-02-14 12:52
@DanBloomberg 

Attached are the files created by `webpio_reg.c`

[no_patch.zip](https://github.com/DanBloomberg/leptonica/files/1724021/no_patch.zip)
[patch.zip](https://github.com/DanBloomberg/leptonica/files/1724022/patch.zip)

**Comment by DanBloomberg** [comment] 2018-02-14 17:25
This is very interesting.  We only have data here for the webp encoder.  Little-endians work fine (for both encoding and decoding; lossy and lossless). The problem is only with big-endians.

For big-endians, the lossy encoder works properly without an endian flip on the pix.

However, the lossless encoder does not: without an endian flip it appears to do G --> A and B --> R.

If we do flip the bytes before doing the lossless encoding, we get B --> R and R --> B.

**Comment by jbreiden** [comment] 2018-02-14 21:11
I'm the Debian Maintainer for Leptonica. Using a big endian PowerPC emulator, webp 0.6.0, leptonica 1.75.2, I can't get this problem to reproduce.

**Comment by jbreiden** [comment] 2018-02-14 21:48
Reproduces with webp 0.6.1. Webp screwed up WebPEncodeLosslessRGBA(). Will inform them.

**Comment by DanBloomberg** [comment] 2018-02-14 22:27
[corrupt.webp.gz](https://github.com/DanBloomberg/leptonica/files/1725853/corrupt.webp.gz)

[good.webp.gz](https://github.com/DanBloomberg/leptonica/files/1725852/good.webp.gz)
Here are the webp images:

    corrupt.webp   (produced on big-endian, lossless, using 0.6.1)
    good.webp    (produced on little-endian, lossless, using 0.6.1)

**Comment by DanBloomberg** [comment] 2018-02-16 01:05
webp team will fix.

leptonica will keep the test for lossless read/write in the regression test webpio_reg.

**Comment by manisandro** [comment] 2018-02-16 01:06
Do you have a reference to the webp issue so that I can track it?

**Comment by DanBloomberg** [comment] 2018-02-16 01:38
All I can tell you is that they fixed the problem on their github master:

https://github.com/webmproject/libwebp/commit/3005237a5d68d1e1f465d925040a9507f55e8895

and I assume that Jeff will be putting out a new debian release soon.

**Comment by manisandro** [comment] 2018-02-16 10:36
Ok thanks, I'll look at backporting that patch to Fedora also.

**Comment by manisandro** [comment] 2018-02-16 19:38
So I backported https://github.com/webmproject/libwebp/commit/3005237a5d68d1e1f465d925040a9507f55e8895 to libwebp-0.6.1, but I still get test failures on big-endian:

    ################   webpio_reg   ###############
    leptonica-1.75.3
    libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1
    Time to read jpg:   0.000
    Time to write webp:   0.002
    Time to read webp:   0.000
    Time to read jpg:   0.000
    Time to write webp:   0.000
    Time to read webp:   0.000
    Time to read jpg:   0.009
    Time to write webp:   0.070
    Time to read webp:   0.010
    Time to read jpg:   0.009
    Time to write webp:   0.558
    Time to read webp:   0.049
    qual = 50, psnr =  43.501
    qual = 75, psnr =  46.071
    qual = 90, psnr =  52.379
    qual = 100, psnr =  57.460
    Lossless write:   0.980 sec
    lossless; psnr should be 1000: psnr =  23.222
    Failure in webpio_reg: value comparison for index 12
    difference = 976.777893 but allowed delta = 0.100000
    Time:   4.326 sec

Produced images are attached.
[data.zip](https://github.com/DanBloomberg/leptonica/files/1732586/data.zip)

**Comment by DanBloomberg** [comment] 2018-02-16 19:58
@manisandro 

Here are the links to the patches.  Can you run them?

 https://chromium-review.googlesource.com/c/webm/libwebp/+/923721
 https://chromium-review.googlesource.com/c/webm/libwebp/+/920981

**Comment by jbreiden** [comment] 2018-02-16 20:13
Use unmodified Leptonica +  webp fixes.

**Comment by manisandro** [comment] 2018-02-16 21:38
Yeah I'm testing with vanilla leptonica-1.75.3 compiled against libwebp-0.6.1 with https://github.com/webmproject/libwebp/commit/3005237 and https://github.com/webmproject/libwebp/commit/d51d03e

**Comment by DanBloomberg** [comment] 2018-02-16 22:21
Be sure you took 1.75.3 today.  The original 1.75.3 that was released on 12 Feb was badly flawed for webp, and it was replaced yesterday evening.  The patch number is  ee301cb, and it is the current 1.75.3 release.

**Comment by manisandro** [comment] 2018-02-16 22:34
I re-downloaded it just to be sure, but still failing. I'll try with latest webp git master to see that I'm not missing any other patches.

**Comment by jbreiden** [comment] 2018-02-16 23:50
Confirmed failure with PowerPC emulator. Image are written correctly, but there is a problem with the reader. Webp team will make another attempt shortly. Thanks for patience on all this!

**Comment by DanBloomberg** [comment] 2018-02-17 01:37
Jeff's emulator now suggests that the images are being written correctly, but there is still a problem reading (uncompressing).  So the images you write should now look OK in the browser, even though the PSNR test is failing.

**Comment by jbreiden** [comment] 2018-02-26 19:10
This patch to Webp 0.6.1 fixes the endian problem. I am now shipping it with Debian. Recommend bringing into Fedora unless you want to wait for 0.6.2.

https://sources.debian.org/patches/libwebp/0.6.1-1/big-endian/
https://sources.debian.org/data/main/libw/libwebp/0.6.1-1/debian/patches/big-endian

**Comment by manisandro** [comment] 2018-02-27 13:44
@jbreiden Thanks, leptonica tests are passing fine now with the patched libwebp.

**Comment by sharkcz** [comment] 2018-02-27 14:07
If you need access to real big endian hw to work on the issue, let me know, we (aka the Fedora Alternative Architectures team) can organize that.

**Comment by jbreiden** [comment] 2018-02-27 17:10
Thanks! Not urgent, but if it is not too hard, please get @stweil access to big endian hardware. I think we are good for webp, but this will be useful for Tesseract, which has some longstanding problem reports with big endian. Tesseract does enough computation to be painfully slow on an emulator.

**Comment by stweil** [comment] 2018-02-28 21:39
Thank you, @jbreiden. Indeed, running an emulated big endian environment needs very much patience, so from time to time I had wished to get access to real hardware for such tests. Are there open issues for big endian Tesseract?

**Comment by jbreiden** [comment] 2018-02-28 22:15
@stweil https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849094

**Comment by sharkcz** [comment] 2018-03-01 08:31
Stefan, please send me an email to sharkcz [at] fedoraproject [dot] org, seems there is no way to communicate directly on github.

**Comment by stweil** [comment] 2018-03-01 13:59
@jbreiden, how can I run the test suite for OCRmyPDF? I did not find enough information on the web - maybe I did not look at the right places.

**Comment by jbreiden** [comment] 2018-03-01 19:19
@jbarlow83  Can you please help identifying the big endian trouble spots? See previous 4 comments.

**Comment by jbarlow83** [comment] 2018-03-01 21:42
@stweil

Git clone ocrmypdf

Setup
```bash
python3 -m venv venv
source venv/bin/activate
pip install .
pip install -r requirements.txt -r test_requirements.txt
```

Test
```bash
pytest tests/tests_main.py::test_monochrome_correlation
pytest tests/tests_main.py::test_autorotate
```

To isolate just the tests that failed.

**Comment by jbreiden** [comment] 2018-03-01 23:33
@stweil @jbarlow83 @DanBloomberg 

Hmmm... this makes me wonder about the makePixelSumTab8() and pixCountPixels() inside pixCorrelationBinary()

https://github.com/DanBloomberg/leptonica/blob/master/src/pix3.c#L2298
https://github.com/DanBloomberg/leptonica/blob/master/src/pix3.c#L1855

**Comment by DanBloomberg** [comment] 2018-03-22 19:20
@jbarlow83 @stweil @jbreiden 

We do not know what caused the big-endian problem on the S390 in Dec 2016, using leptonica 1.73.

Jeff checked pixCorrelationBinary() and it was endian-independent, so not the problem.

There may have been a configuration issue, where for some reason on the S390 the endian environmental variable was set to L_LITTLE_ENDIAN.  That should be checked.

The originating issue here was a webp bug on big-endians, which has been fixed.  I will close this bug in a week unless there is a reason to keep it open.  Perhaps a more recent version of tesseract/leptonica on the S390 will work properly.

**Comment by DanBloomberg** [comment] 2018-03-24 01:34
Closing this issue.

**Closed by DanBloomberg** 2018-03-24 01:34 UTC

**Comment by stweil** [comment] 2018-05-05 14:48
Tesseract for S390 and other big endian machines was fixed [recently](https://github.com/tesseract-ocr/tesseract/commit/21d5ce57175e35e9df514e81f9c584f0bb2910ad).
