### ISSUE TITLE
1.74.2  FAIL: mtiff_reg.exe

### ISSUE THREAD

**Issue by matzeri** [DanBloomberg/leptonica#250] opened 2017-05-25 10:11 UTC
On cygwin both 32bit and 64bit the test mtiff_reg.exe fails.
For what I see the test is not present on 1.74.1

################   mtiff_reg   ###############
leptonica-1.74.2
libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.5.0) : libpng 1.6.28 : libtiff 4.0.6 : zlib 1.2.11 : libwebp 0.4.4 : libopenjp2 2.1.2

Info in pixaReadMultipageTiff:  Tiff: 7 pages
Info in boxaWriteMem: work-around: writing to a temp file
Info in boxaWriteMem: work-around: writing to a temp file
Info in boxaWriteMem: work-around: writing to a temp file
Info in boxaWriteMem: work-around: writing to a temp file
Info in boxaWriteMem: work-around: writing to a temp file
Info in pixaReadMultipageTiff:  Tiff: 1000 pages
Time to read 1000 images and return a pixa:  0.078 sec
Info in boxaWriteMem: work-around: writing to a temp file
Info in boxaWriteMem: work-around: writing to a temp file
Writing to: /tmp/lept/tiff/weasel4.ps
Writing to: /tmp/lept/tiff/weasel4.pdf
Info in pixaReadMultipageTiff:  Tiff: 4 pages
Failure in mtiff_reg, index 18: comparing /tmp/lept/tiff/weasel_orig.tif with /tmp/lept/golden/mtiff_golden.18.tif
 Tiff: 4 page
Failure in mtiff_reg, index 21: comparing /tmp/lept/tiff/weasel_rev.tif with /tmp/lept/golden/mtiff_golden.21.tif
Failure in mtiff_reg, index 22: comparing /tmp/lept/tiff/weasel_rev_rev.tif with /tmp/lept/golden/mtiff_golden.22.tif
Time:   2.059 sec

**Comment by DanBloomberg** [comment] 2017-05-26 18:27
Thank you for reporting this problem on cygwin.  We're investigating.

**Comment by DanBloomberg** [comment] 2017-05-28 01:01
This has been  perplexing.  It may be related to tiff initialization issues with 2 bpp,
because it only seems to happen with 2 bpp debug.  And when you run with dbg
there is no problem, which strongly hints at an initialization issue on cygwin
 (Well, there are a couple of other non-related bugs that will get fixed).

Our cygwin expert has verified the bug with tiff 4.0.3 as well.  Is it possible for you to
try an earlier version of the library, say 3.9.5?

**Comment by matzeri** [comment] 2017-05-30 08:42
I will need to build the the 3.9.5 lib version as currently only 4.0.x is available as standard cygwin package.
It could take a while.

**Comment by DanBloomberg** [comment] 2017-05-30 15:08
Don't bother.  We finally solved the problem yesterday, and I will be posting later today.

**Comment by DanBloomberg** [comment] 2017-05-30 18:49
The issue has been fixed by David Bryan.

It only exists on Windows.  There were 3 problems:
1. lept_mkir() was giving an error on windows if the directory already existed
2. the unix path was being passed to fopenTiff(), which couldn't translate to Windows path
3. under Windows, the tiff library uses the pad bits in the scanline (if there are any) in deriving the compressed string. This is not a bug in the tiff library, because  when uncompressed back to a raster, the images are the same.  It's only a problem if you compare the compressed tiff file, byte-by-byte, with a golden file that could have been made with different pad bits.

The fix for (3)  is to set the pad bits to 0 before writing.  This has been done for all formatted writes that use an external library to compress the image.

**Closed by DanBloomberg** 2017-05-30 18:49 UTC
